---
title: "benchmark_tuning.Rmd"
author: "Ethan Greig"
date: "1/20/2019"
output: html_document
---

```{r, include=FALSE}
library(knitr)
source(purl('random_forest_tuning.Rmd', output = tempfile()))
# Note that only data from 2008-2017 is imported here. 2018 data is kept as a holdout set
```

## Hyperparameter Tuning on RF model
```{r}
# Grids attempted:
#rf_grid(df, mtrys=1:25, nodesizes=1:25)
#rf_grid(df, mtrys=1:15, nodesizes=16:35)
#rf_grid(df, mtrys=1:8, nodesizes=28:60)
#rf_grid(df, mtrys=2:8, nodesizes=50:69)
#rf_grid(df, mtrys=2:8, nodesizes=50:59, ntrees=6000)
rf_grid(df, mtrys=2:8, nodesizes=55:65, ntrees=10000)

# result: mtry=6, nodesize=60
```

```{r, include=FALSE}
library(knitr)
source(purl('cross_validation.Rmd', output = tempfile()))
# defines the cross-validation functions
```

## Calculate Tuned Random Forest (Regression) Performance
```{r}
cv_rf_reg(df, nfolds=10, nruns=32, mtry=6, nodesize=60)
# BENCHMARK
# Log Loss: 0.675 (sd 0.11)
# Accuracy: 62.4% (sd 0.12)

# AFTER TUNING
# Log Loss: 0.652 (sd 0.08)
# Accuracy: 63% (sd 0.12)
```

## Calculate Tuned Random Forest (Classification) Performance
```{r}
cv_rf_class(df, nfolds=10, nruns=24, mtry=6, nodesize=60)
# BENCHMARK
# Log Loss: 0.672 (sd 0.11)
# Accuracy: 62.5% (sd 0.12)

# AFTER TUNING
# Log Loss: 0.672 (sd 0.10)
# Accuracy: 62.2% (sd 0.11)
#(same)
```