---
title: "NHL Playoff Wins Analysis"
author: "Ethan Greig"
date: "3/4/2018"
output: pdf_document
---

## Import Data
```{r}
library(randomForest)
stats <- c('GF%', 'AdjGF%', '5v5_xGF%', '5v5_CF%', 'Time_Led', '5v5_Sh%', '5v5_Sv%', 'PP%', 'PK%', 'ROWins')

dStats <- stats
for (i in 1:length(stats)) {
  stat <- stats[i]
  dStat <- paste0('d', stat)
  dStats[i] <- dStat
}

logLoss <- function(pred, actual){
  -1*mean(log(pred[model.matrix(~ actual + 0) - pred > 0]))
}

mse <- function(pred, actual){
  mean((pred-actual)^2)
}

acc <- function(pred, actual){
  wlpred <- round(pred, 0)
  correct <- wlpred==actual
  num_correct <- sum(correct, na.rm=TRUE)
  return(num_correct/length(correct))
}

corsica1 <- read.csv("input_csvs/corsica_5v5_08-17.csv", check.names=FALSE)
corsica1$Season <- strtoi(substr(corsica1$Season, 6, 9))
corsica1 <- corsica1[, c('Team', 'Season', 'CF%', 'GF%', 'xGF%', 'Sh%', 'Sv%')]

corsica2 <- read.csv("input_csvs/corsica_all_08-17.csv", check.names=FALSE)
corsica2$Season <- strtoi(substr(corsica2$Season, 6, 9))
corsica2 <- corsica2[, c('Team', 'Season', 'allGF%', 'allGF', 'allGA')]

morestats <- read.csv("input_csvs/misc_stats_playoffwins_08-17.csv", check.names=FALSE)
morestats <- morestats[, c('Team', 'Season', 'HDCF', 'Time Led', 'Playoff Wins', 'GF_EN', 'GA_EN', 'PP%', 'PK%', 'W', 'ROW')]

raw_data <- merge(merge(corsica1, corsica2, by=c("Team", "Season")), morestats, by=c("Team", "Season"))
raw_data$`AdjGF%` <- with(raw_data, round(100*(allGF-GF_EN)/(allGF-GF_EN+allGA-GA_EN),2))
raw_data <- raw_data[, c('Team', 'Season', 'allGF%', 'AdjGF%', 'xGF%', 'CF%', 'Time Led', 'Sh%', 'Sv%', 'PP%', 'PK%', 'ROW', 'Playoff Wins')]
colnames(raw_data) <- c('Team', 'Season', stats, 'Playoff_Wins')

adj_data_10 <- raw_data[raw_data$`Playoff_Wins`>=0,]
adj_data_10 <- adj_data_10[,c('Team', 'Season', stats)]

corsica1_pred <- read.csv("input_csvs/2018/corsica_5v5_18.csv", check.names=FALSE)
corsica1_pred$Season <- 2018
corsica1_pred <- corsica1_pred[, c('Team', 'Season', 'CF%', 'GF%', 'xGF%', 'Sh%', 'Sv%')]

corsica2_pred <- read.csv("input_csvs/2018/corsica_all_18.csv", check.names=FALSE)
corsica2_pred$Season <- 2018
corsica2_pred <- corsica2_pred[, c('Team', 'Season', 'allGF%', 'allGF', 'allGA')]

morestats_pred <- read.csv("input_csvs/2018/misc_stats_playoffwins_18.csv", check.names=FALSE)
morestats_pred$Season <- 2018
morestats_pred <- morestats_pred[, c('Team', 'Season', 'Time Led', 'GF_EN', 'GA_EN', 'PP%', 'PK%', 'ROW')]

playoff_teams_2018 <- merge(merge(corsica1_pred, corsica2_pred, by=c("Team","Season")), morestats_pred, by=c("Team","Season"))
playoff_teams_2018$`AdjGF%` <- with(playoff_teams_2018, round(100*(allGF-GF_EN)/(allGF-GF_EN+allGA-GA_EN),2))
playoff_teams_2018 <- playoff_teams_2018[, c('Team', 'Season', 'allGF%', 'AdjGF%', 'xGF%', 'CF%', 'Time Led', 'Sh%', 'Sv%', 'PP%', 'PK%', 'ROW')]
colnames(playoff_teams_2018) <- c('Team', 'Season', stats)


series <- read.csv("input_csvs/all_playoff_series.csv")
series$Home_Won <- round(series$Home_W., 0)
for(i in 1:length(dStats)) {
  dStat <- dStats[i]
  series[,dStat] <- NA
}

all_regular_season_data <- adj_data_10[, c('Team', 'Season', stats)]
all_regular_season_data <- rbind(all_regular_season_data, playoff_teams_2018)

getDifferences <- function(row, df) {
  df_year <- df[df$Season==row$Season,]
  a1 <- df_year[as.character(df_year$Team)==as.character(row$Home),]
  a2 <- df_year[as.character(df_year$Team)==as.character(row$Away),]
  for (i in 1:length(stats)) {
    stat <- stats[i]
    dStat <- dStats[i]
    row[dStat] <- a1[[stat]] - a2[[stat]]
  }
  return(row)
}

for (row in 1:nrow(series)) {
  series[row,] <- getDifferences(series[row,], all_regular_season_data)
}

head(series)
colMeans(series[,dStats])
```


## Organize Data, Select Model, Build Model, Predict
```{r}
stats <- c('GF%', 'AdjGF%', '5v5_xGF%', '5v5_CF%', 'Time_Led', '5v5_Sh%', '5v5_Sv%', 'PP%', 'PK%', 'ROWins')

dStats <- stats
for (i in 1:length(stats)) {
  stat <- stats[i]
  dStat <- paste0('d', stat)
  dStats[i] <- dStat
}

default_num_factors <- 3
Comps <- NULL
for (i in 1:default_num_factors) {
  Comps[i] <- paste0('Comp.', i)
}

## dataset contains Team, Season, Round, dStats, and Home_Won
pca_create <- function(series_dataset, year, round) {
  dStat_table <- series_dataset[,dStats]
  dStat_table_flip <- -series_dataset[,dStats]
  pca <- princomp(rbind(dStat_table, dStat_table_flip), cor=TRUE)

  prin_data <- series_dataset[,c('Season', 'Round', 'Home', 'Away', 'Home_Won')]
  prin_data_flip <- series_dataset[,c('Season', 'Round', 'Home', 'Away', 'Home_Won')]
  orig_home <- prin_data_flip$Home
  prin_data_flip$Home <- prin_data_flip$Away
  prin_data_flip$Away <- orig_home
  prin_data_flip$Home_Won <- 1 - prin_data_flip$Home_Won
  prin_data <- rbind(prin_data, prin_data_flip)
  prin_data <- cbind(prin_data, pca$scores)
  
  prin_data$Home_Won[prin_data$Season==year & prin_data$Round>=round] <- NA
  return(prin_data)
}

pca_glm <- function(pca_dataset, comps=Comps) {
  dataset <- pca_dataset[,c(comps, 'Home_Won')]
  model <- suppressWarnings(glm(`Home_Won` ~ .,data=dataset, weights=rep(0.5, nrow(dataset)), family=binomial(link='logit')))
  return(model)
}

pca_validate <- function(pca_dataset) {
  pca_validations <- matrix(0,nrow=7, ncol=4)
  colnames(pca_validations) <- c('Components', 'Log Loss', 'MSE', 'Accuracy')
  
  Comps <- c('Comp.1', 'Comp.2')
  pca_validations[1,1] <- "Comp.1, Comp.2"
  pca_validations[1,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  Comps <- c('Comp.1', 'Comp.3')
  pca_validations[2,1] <- "Comp.1, Comp.3"
  pca_validations[2,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  Comps <- c('Comp.1', 'Comp.2', 'Comp.3')
  pca_validations[3,1] <- "Comp.1, Comp.2, Comp.3"
  pca_validations[3,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  Comps <- c('Comp.1', 'Comp.2', 'Comp.4')
  pca_validations[4,1] <- "Comp.1, Comp.2, Comp.4"
  pca_validations[4,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  Comps <- c('Comp.1', 'Comp.3', 'Comp.4')
  pca_validations[5,1] <- "Comp.1, Comp.3, Comp.4"
  pca_validations[5,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  Comps <- c('Comp.1', 'Comp.2', 'Comp.3', 'Comp.4')
  pca_validations[6,1] <- "Comp.1, Comp.2, Comp.3, Comp.4"
  pca_validations[6,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  Comps <- c('Comp.1', 'Comp.2', 'Comp.3', 'Comp.4', 'Comp.5')
  pca_validations[7,1] <- "Comp.1, Comp.2, Comp.3, Comp.4, Comp.5"
  pca_validations[7,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  
  # Comps <- c('Comp.1', 'Comp.3')
  # for (num in 2:num_comps) {
  #   Comps <- NULL
  #   for (i in 1:num) {
  #     Comps[i] <- paste0('Comp.', i)
  #   }
  #   pca_validations[num,1] <- paste0('up to Comp.', num)
  #   pca_validations[num,2:4] <- pca_iterate_validation(pca_dataset, Comps)
  # }
  return(pca_validations)
}

pca_iterate_validation <- function(pca_dataset, comps, iterations=125) {
  iteration_errors <- matrix(NA, nrow=iterations, ncol=3)
  colnames(iteration_errors) <- c("Log Loss Binary", "Mean Squared Error Binary", "Mean Accuracy")
  for (i in 1:iterations) {
    iteration_errors[i,] <- pca_cross_validate(pca_dataset, comps)
  }
  return(round(colMeans(iteration_errors),3))
}

pca_cross_validate <- function(pca_dataset, comps) {
  pca_dataset_shuffled <- pca_dataset[sample(nrow(pca_dataset)),]
  folds <- cut(seq(1,nrow(pca_dataset_shuffled)),breaks=10,labels=FALSE)
  
  log_loss <- NA
  mse <- NA
  accuracy <- NA
  
  for (i in 1:10) {
    testRows <- which(folds==i,arr.ind=TRUE)
    test_data <- pca_dataset_shuffled[testRows,]
    train_data <- pca_dataset_shuffled[-testRows,]
    
    fold_model <- pca_glm(train_data, comps)
    
    test_data$bin_pred <- predict(fold_model, test_data[,comps], type='response')
  
    log_loss[i] <- logLoss(test_data$bin_pred, test_data$Home_Won)
    mse[i] <- mse(test_data$bin_pred, test_data$Home_Won)
    accuracy[i] <- acc(test_data$bin_pred, test_data$Home_Won)
  }
  return(c(mean(log_loss), mean(mse), mean(accuracy)))
}

select_model <- function(series_dataset, year, round) {
  data_up_to_year <- series_dataset[series_dataset$Season<=year,]
  data_up_to_round <- series_dataset[series_dataset$Season<year | series_dataset$Round<=round,]
  pca_dataset <- pca_create(data_up_to_round, year=year, round=round)
  return(pca_validate(na.omit(pca_dataset)))
}

predict_round <- function(series_dataset, year, round) {
  Comps <- c("Comp.1", "Comp.2", "Comp.3")
  data_up_to_year <- series_dataset[series_dataset$Season<=year,]
  data_up_to_round <- series_dataset[series_dataset$Season<year | series_dataset$Round<=round,]
  pca_dataset <- pca_create(data_up_to_round, year=year, round=round)
  model <- pca_glm(na.omit(pca_dataset), Comps)
  pca_dataset <- pca_dataset[pca_dataset$Season==year & pca_dataset$Round==round,c('Home', 'Away', 'Round', 'Home_Won', Comps)]
  pca_dataset$prediction <- predict(model, pca_dataset[,Comps], type='response')
  pca_dataset$LogLoss <- with(pca_dataset, log(abs(1 - prediction - Home_Won)))
  return(pca_dataset[1:(nrow(pca_dataset)/2),c('Home', 'Away', 'Round', Comps, 'prediction', 'LogLoss')])
}
```

```{r}
select_model(series, 2018, 1)
```

```{r}
predict_round(series, 2018, 2)
```