---
title: "rf_final_tuning.Rmd"
author: "Ethan Greig"
date: "1/27/2019"
output: html_document
---

```{r, include=FALSE}
library(knitr)
source(purl('random_forest_tuning.Rmd', output = tempfile()))
source(purl('cross_validation.Rmd', output = tempfile()))
source(purl('rf_feature_selection.Rmd', output = tempfile()))
```

## Define subsets of full features
```{r}
df_unpaired <- df[,c('Home_Won', dStats_unpaired)]
df_9 <- df[,c('Home_Won', dStats_9)]
df_5 <- df[,c('Home_Won', dStats_5)]
```

## Hyperparameter Tuning on reduced feature set RF (unpaired features)
```{r}
# Grid Search using randomForest's built in OOB error (not cross-validated Log Loss).
# rf_grid outputs mean + sd/5 of log loss error, find minimum value over grid of hyperparameters

# Grids attempted:
#rf_grid(df_unpaired, mtrys=1:2, nodesizes=50:170, ntrees=5000)
#rf_grid(df_unpaired, mtrys=1, nodesizes=105:135, ntrees=30000)
rf_grid(df_unpaired, mtrys=1, nodesizes=110:130, ntrees=100000)

# result: mtry=1, nodesize=118
```

## Hyperparameter Tuning on reduced feature set RF (9 best features)
```{r}
# Grid Search using randomForest's built in OOB error (not cross-validated Log Loss)
# rf_grid outputs mean + sd/5 of log loss error, find minimum value over grid of hyperparameters

# Grids attempted:
#rf_grid(df_9, mtrys=1:3, nodesizes=40:155, ntrees=5000)
#rf_grid(df_9, mtrys=1, nodesizes=125:155, ntrees=30000)
rf_grid(df_9, mtrys=1, nodesizes=135:155, ntrees=150000)

# result: mtry=1, nodesize=141
```

## Hyperparameter Tuning on test feature set RF (5 test features)
```{r}
# Grid Search using randomForest's built in OOB error (not cross-validated Log Loss)
# rf_grid outputs mean + sd/5 of log loss error, find minimum value over grid of hyperparameters

# Grids attempted:
#rf_grid(df_5, mtrys=1, nodesizes=40:155, ntrees=5000)
rf_grid(df_5, mtrys=1, nodesizes=106:154, ntrees=20000)

# result: mtry=1, nodesize=129
```

## Random Forest (Regression) Performance, Tuned on subsets of features
```{r}
# FULL FEATURES
# Log Loss: 0.660 (sd 0.05)
# Accuracy: 61%

cv_rf_reg(df_unpaired, nfolds=11, nruns=64, mtry=1, nodesize=118, ntrees=8000)
# Log Loss: 0.662 (sd 0.04)
# Accuracy: 60%

cv_rf_reg(df_9, nfolds=11, nruns=64, mtry=1, nodesize=141, ntrees=8000)
# Log Loss: 0.656 (sd 0.04)
# Accuracy: 60%

cv_rf_reg(df_5, nfolds=11, nruns=64, mtry=1, nodesize=129, ntrees=8000)
# Log Loss: 0.645 (sd 0.05)
# Accuracy: 64%

```

